#ifndef COLORS_H
#define COLORS_H

#define TXT_RED			FOREGROUND_RED|FOREGROUND_INTENSITY
#define TXT_BLUE		FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define TXT_GREEN		FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define TXT_YELLOW		FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define TXT_CYAN		FOREGROUND_BLUE|FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define TXT_PINK		FOREGROUND_RED|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define TXT_DRKBLUE		FOREGROUND_BLUE
#define TXT_DRKGREEN	FOREGROUND_GREEN
#define TXT_WHITE		FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define TXT_GRAY		FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE

#endif
